field: a185f2b9-54ad-4fb8-b82b-af8804730d7e # Lyric
fieldLayouts:
  53754dfd-8cff-46b3-8ba6-bd30affb1bac:
    tabs:
      -
        elements:
          -
            fieldUid: c00caedc-9fc8-43d8-8e02-26a586934f07 # Nomor
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 39b8fc54-87d2-4fea-a0b1-f3c967a7ca49 # Lirik
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  39b8fc54-87d2-4fea-a0b1-f3c967a7ca49: # Lirik
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: lirik
    instructions: ''
    name: Lirik
    searchable: false
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      cleanupHtml: true
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: ''
      purifyHtml: '1'
      redactorConfig: ''
      removeEmptyTags: '1'
      removeInlineStyles: '1'
      removeNbsp: '1'
      showHtmlButtonForNonAdmins: ''
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
  c00caedc-9fc8-43d8-8e02-26a586934f07: # Nomor
    columnSuffix: null
    contentColumnType: integer(10)
    fieldGroup: null
    handle: nomor
    instructions: ''
    name: Nomor
    searchable: false
    settings:
      decimals: 0
      defaultValue: null
      max: null
      min: 0
      prefix: null
      previewCurrency: ''
      previewFormat: decimal
      size: null
      suffix: null
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Number
handle: bait
name: Bait
sortOrder: 1
