field: a185f2b9-54ad-4fb8-b82b-af8804730d7e # Lyric
fieldLayouts:
  0c8b842b-fc1e-465c-ba7e-e5f6ec50bfd4:
    tabs:
      -
        elements:
          -
            fieldUid: 1a7d2d9f-a304-4af7-b3da-7a8d6b6cab7e # Nomor
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 44dd785d-1cf0-439d-ab55-abb3542a1f2a # Lirik
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  1a7d2d9f-a304-4af7-b3da-7a8d6b6cab7e: # Nomor
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: nomor
    instructions: ''
    name: Nomor
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  44dd785d-1cf0-439d-ab55-abb3542a1f2a: # Lirik
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: lirik
    instructions: ''
    name: Lirik
    searchable: false
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      cleanupHtml: true
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: ''
      purifyHtml: '1'
      redactorConfig: ''
      removeEmptyTags: '1'
      removeInlineStyles: '1'
      removeNbsp: '1'
      showHtmlButtonForNonAdmins: ''
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
handle: reff
name: Reff
sortOrder: 2
