columnSuffix: fgkqydni
contentColumnType: text
fieldGroup: ffd2cfe8-bb52-465e-93ed-fc6bc9af908e # Common
handle: customTitle
instructions: ''
name: 'Custom Title'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '4'
  multiline: ''
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
