columnSuffix: null
contentColumnType: string
fieldGroup: ffd2cfe8-bb52-465e-93ed-fc6bc9af908e # Common
handle: popularAlbum
instructions: ''
name: 'Popular Album'
searchable: false
settings:
  contentTable: '{{%stc_popularalbum}}'
  fieldLayout: matrix
  maxRows: ''
  minRows: ''
  placeholderKey: null
  propagationKeyFormat: null
  propagationMethod: all
  selectionLabel: ''
  staticField: '1'
translationKeyFormat: null
translationMethod: site
type: verbb\supertable\fields\SuperTableField
