field: 3458a78a-a619-4cdc-b887-9e233a2db833 # Popular Lyric
fieldLayouts:
  6506dacf-53f1-46cb-b869-2ec48431edb6:
    tabs:
      -
        elements:
          -
            fieldUid: e0018da9-7ddc-47f9-9829-2610640f37c4 # Main Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: e0d0af34-530a-4a46-aab6-798a2a9939db # Secondary Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  e0d0af34-530a-4a46-aab6-798a2a9939db: # Secondary Text
    columnSuffix: cgssicoi
    contentColumnType: text
    fieldGroup: null
    handle: secondaryText
    instructions: ''
    name: 'Secondary Text'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: '1'
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  e0018da9-7ddc-47f9-9829-2610640f37c4: # Main Text
    columnSuffix: bwhixsno
    contentColumnType: text
    fieldGroup: null
    handle: mainText
    instructions: ''
    name: 'Main Text'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
