field: c070fb45-2321-447d-961a-6baf7e632d60 # Banner
fieldLayouts:
  135e4812-43ee-45dc-8e83-b21e8900307a:
    tabs:
      -
        elements:
          -
            fieldUid: 0e49d1ef-9990-4158-b456-2383238d94e0 # Main Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: ccffd80f-89dd-4393-8eed-9d59c74e6455 # Secondary Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 141058d7-d366-41fe-b12f-765432ac8c83 # Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 2a061694-ae48-4141-b0c9-bbecc960c229 # Number
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  0e49d1ef-9990-4158-b456-2383238d94e0: # Main Text
    columnSuffix: rfnltmdn
    contentColumnType: text
    fieldGroup: null
    handle: mainText
    instructions: ''
    name: 'Main Text'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  2a061694-ae48-4141-b0c9-bbecc960c229: # Number
    columnSuffix: axbatqii
    contentColumnType: text
    fieldGroup: null
    handle: number
    instructions: ''
    name: Number
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  141058d7-d366-41fe-b12f-765432ac8c83: # Image
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: image
    instructions: ''
    name: Image
    searchable: false
    settings:
      allowSelfRelations: false
      allowUploads: true
      allowedKinds: null
      defaultUploadLocationSource: 'volume:3f7d4197-4e68-40ca-86ca-c0357cdb4628' # Images
      defaultUploadLocationSubpath: ''
      limit: ''
      localizeRelations: false
      previewMode: full
      restrictFiles: ''
      selectionLabel: ''
      showSiteMenu: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      singleUploadLocationSource: 'volume:3f7d4197-4e68-40ca-86ca-c0357cdb4628' # Images
      singleUploadLocationSubpath: ''
      source: null
      sources: '*'
      targetSiteId: null
      useSingleFolder: false
      validateRelatedElements: false
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  ccffd80f-89dd-4393-8eed-9d59c74e6455: # Secondary Text
    columnSuffix: crutzlyy
    contentColumnType: text
    fieldGroup: null
    handle: secondaryText
    instructions: ''
    name: 'Secondary Text'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: '1'
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
