defaultPlacement: end
enableVersioning: true
handle: home
name: Home
propagationMethod: all
siteSettings:
  9186e763-3071-416b-aa22-77e22be0bb2d: # Nyanyian Surga
    enabledByDefault: true
    hasUrls: true
    template: null
    uriFormat: __home__
type: single
