defaultPlacement: end
enableVersioning: true
handle: lagu
name: Lagu
propagationMethod: all
siteSettings:
  9186e763-3071-416b-aa22-77e22be0bb2d: # Nyanyian Surga
    enabledByDefault: true
    hasUrls: true
    template: null
    uriFormat: 'lagu/{slug}'
structure:
  maxLevels: 2
  uid: d3bc57c0-2853-4c34-b551-77422ce05703
type: structure
